# trigger: none
resources:
  pipelines:
  - pipeline: eshoponweb-ci-dockercompose
    source: eshoponweb-ci-dockercompose # given pipeline name
    trigger: true
  repositories:
    - repository: self
      trigger: none

variables:
  location: 'northeurope'
  templateFile: 'infra/aci.bicep'
  subscriptionid: 'abcc12e8-46f6-4fb0-ae1f-86a92dafdaa7'
  azureserviceconnection: 'Azure subscription 1 (abcc12e8-46f6-4fb0-ae1f-86a92dafdaa7)'
  webappname: 'az400eshop-danasoft'
  acr-login-server: 'crs76mr33rynqts.azurecr.io'
  acr-username: 'crs76mr33rynqts'
  resource-group: 'AZ400-EWebShop-danasoft' 


stages:
- stage: Deploy
  displayName: Docker Compose to ACI
  #variable group referencing KV secret
  variables:
  - group: 'eshopweb-vg'
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Deploy Azure Container Instance using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACI Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: ' -name $(webappname) -image $(acr-login-server)/eshopwebmvc:latest -server $(acr-login-server) -username $(acr-username) -password $(acr-secret)'
        deploymentMode: 'Incremental'
        # deploymentOutputs: 'asp-json'
    