# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  tag: '$(Build.BuildId)'
  resource-group: 'AZ400-EWebShop-danasoft'
  location: 'northeurope'
  templateFile: 'infra/acr.bicep'
  azureserviceconnection: 'azure subs'
  subscriptionId: 'abcc12e8-46f6-4fb0-ae1f-86a92dafdaa7'

stages:
- stage: Build
  displayName: Create ACR for images
  jobs:
  - job: Build
    pool:
      name: eShopOnWebSelfPool
      demands: Agent.Name -equals eShopOnWebSelfAgent
    steps:
    #Create ACR to keep docker images
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACR Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureserviceconnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'acr-json'
    
    #Parse ACR login server variable
    - task: PowerShell@2
      displayName: Parse Bicep Output
      inputs:
        targetType: 'inline'
        script: |
          $var=ConvertFrom-Json '$(acr-json)'
          $value=$var.acrloginServer.value
          Write-Host "##vso[task.setvariable variable=acrloginserver;]$value"
          echo $acrloginserver
    # docker compose build images
    - task: DockerCompose@1
      displayName: Build Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureserviceconnection)'
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Build services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
    - task: DockerCompose@1
      displayName: Push Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureserviceconnection)
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Push services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
